### ISSUE TITLE
Spring FOSS Family Dinner

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#102]
Since the last full week of classes we don't have our room for FOSS (Wednesday, April 24th), we want to do the FOSS family dinner that night. 

Group Raise Me Link:
https://www.groupraise.com/restaurants/search?lat=43.0812766&lng=-77.67518760000002

**Comment by jwflory** [comment]
Is it possible to finalize a date by Wednesday, Feb. 27th? This helps with advance planning I'm looking at in April.

**Comment by jibby0** [comment]
We've agreed on a date: the Wednesday of the last full week of classes (April 24th), during normal FOSS hours (5-7).

Due to the issues we've had with GroupRaise, and the fact we've met our fundraising goal for the year, we've decided to not use GroupRaise to organize this meal. (To the RITLug treasurer of 2019-2020: you're welcome.)

This may not even be a fundraising meal. Just a meet & eat.

A poll will be put up shortly, to find a suitable restaurant for RITLug members and FOSS friends. The poll should be sent to RITLug's announcements channel, FOSS IRC, and the FOSS mailing list. Maybe mentioned at our weekly meeting.

**Comment by jibby0** [comment]
I'll email SJ, asking about potential restaurant options. I'll also spur discussion about it next FOSS hours, so we can get a good list to start with, before a poll goes up.

**Comment by jibby0** [comment]
SJ's recommendations are:

 - Bar Louie, kind of modernized bar food. Probably supports a wide range of dietary needs.
 - King and I Thai.  See above.
 - Tandoor, Indian see above.
 - Sticky lips has good veg food too, and might be worth a repeat.

We'll discuss these at FOSS hours on Wednesday, and pick one.

**Comment by Tjzabel** [comment]
We've chosen sticky lips.

**Comment by Tjzabel** [comment]
Event complete! :tada: :tada: Great thanks to all the FOSS Folks for coming out for the night!
