### ISSUE TITLE
Create Teleirc Logo

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#116]
Currently, Teleirc does not have any sort of logo, and it would be great to have one as the project grows larger and gains more traction. 

At the moment, @jwflory and I have reached out to Ura Design who created our new RITlug logo, to see if they have any bandwidth or interest to create a Teleirc logo. Next steps are to follow up with them, and talk within our eboard to see if a logo is something we want to pay for with our budget.

The ultimate goal with this issue is to have small cards with a beautiful logo and short description of teleirc to hand out at ImagineRIT to spread awareness of the project.

**Comment by jwflory** [comment]
_Discussed in 2019-03-30 Teleirc developer meeting._

---

This ticket is on hold until the logo design is finalized. Because we have a tight timeline for Imagine RIT, we decided to plan on producing Teleirc stickers for Imagine on April 27th.

We will push the brochures to the summer and hopefully have them ready in time for the fall semester RIT Club Gala.

cc: @elioqoshi @anxh3l0

**Comment by elioqoshi** [comment]
Should be doable next week. We are traveling this week (IFF and SFK) so hence the delayed replies :)

Tracking also here on our repo: 
https://github.com/uracreative/works/issues/30

**Comment by Tjzabel** [comment]
Teleirc logo is now live! https://github.com/RITlug/teleirc/tree/master/brand
