### ISSUE TITLE
Off-board ctmartin

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#124]
Due to limits on my personal bandwidth I have agreed to put down my position as Project Coordinator. As such, [standard off-boarding procedures](http://runbook.ritlug.com/administration/eboard-onboarding-offboarding/#off-boarding-outgoing-eboard) will need to be followed.

From the runbook:
* [x] Remove as officer in CampusGroups
* [x] Remove as Slack admin
* [x] Remove from Slack `#eboard` channel
* [x] Remove GitHub org admin rights
* [x] Revoke access to the RITlug Google Drive
* [ ] Remove admin privileges on RITlug's IRC channels
* [x] Remove admin privileges on RITlug's Telegram groups
* [x] Remove access to all RITlug servers, including
  * [x] Titan (@Serubin has been informed via Telegram private chat, pending confirmation of access removal)
  * [ ] TigerOS Mirrors
  * [x] Private GitLab
  * [x] TigerOS Builder (if not rebuilt from scratch)
  * [ ] Nextcloud
  * [ ] CBET/new servers
  * [ ] Possibly others
* [x] Change any passwords you [eboard] feel you need to

Additionally, outside of the runbook, the following will need to happen:
* [x] Remove access to RITlug group on GitLab.com
* [x] Remove access to eboard group on private GitLab
* [x] Remove from `eboard@` & `projects@` emails
* [x] Remove [me as the assignee from any issues in the RITlug org](https://github.com/search?q=assignee%3Act-martin+is%3Aopen+org%3ARITlug&type=Issues)
* [x] Arrange for removal of server from IST lab (see RITlug/infrastructure#17)
* [x] @Tjzabel will be the new TigerOS Lead, that change should also be documented where relevant (see RITlug/TigerOS#155)

**Comment by Serubin** [comment]
I can't edit this issue, however direct titan access has been removed.

**Comment by Tjzabel** [comment]
@Serubin thanks for doing that.

**Comment by Tjzabel** [comment]
As an update on my end, @ct-martin has been removed from just about all services. 

For IRC, I am going to keep you on your current perms, since you still use it a decent amount. Going forward, I am not sure if we are going to be adding new eboard members to the IRC channel(s) very often. Of all the current eboard, I am the only one who uses IRC/Matrix regularly, so I am leaving you on. If you really would like to be demoted on IRC, let me know and I can do so.

Of all issues assigned, all but some TigerOS ones have been removed. The TigerOS issues are somewhat deprecated, and I will handle those as we finish the transition off GitHub. Also, since the TigerOS mirrors and other servers aren't strictly eboard-related, I am going to leave those there for the time being. 

Everything else should be done :tada: :tada:
