### ISSUE TITLE
Poster Redesign

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#28]
The current posters we are using have a handful of issues, including that they don't always print well.

Goals of the new poster template:
* Works in Black & White, and Color (there can be two templates if needed, but this also may add work in the future)
* Make sure it has the website on it
* Clean design (white background, don't need to fill every inch)
* Pics, but also don't overdo it

**Comment by jflory7** [comment]
@ct-martin Could you submit a pull request to [RITlug/brand](https://github.com/RITlug/brand) and replace the [template poster](https://github.com/RITlug/brand/blob/master/poster/template.svg) with the file you currently have?

**Comment by jflory7** [comment]
This is now complete. The updated poster is [in RITlug/brand](https://github.com/RITlug/brand/tree/master/poster). There is still an issue with the font, but I will file a new issue to keep track of that (since it not a blocking issue and is a minor annoyance).

@ct-martin++ Thanks for the help on the new design! :+1:
