### ISSUE TITLE
Figure out Facebook

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#41]
We have a Facebook apparently. Wait, you're surprised? Most of us were too.

What do we want to do with it?
* Close it
* Set up an IFTTT hook to just repost the website
  * Easy low-maintenance way to keep a presence

**Comment by Tjzabel** [comment]
I _personally_ think we should just remove the Facebook page. I do agree it would be a low-maintenance way to keep some sort of presence, so let me know what y'all think.

**Comment by jwflory** [comment]
@Tjzabel Without resources to moderate and maintain it, I think it's better to close it out. We could maintain it, but in the event something comes up where someone says something inappropriate or disrespectful to someone else, but nobody is keeping up with the page, it could reflect poorly on us.

**Comment by Tjzabel** [comment]
@jwflory I'm all for closing out the page. It would be a good idea to post once more pointing to campusgroups/slack/twitter etc so members who are only subscribed to the group know where else to look for us

**Comment by ct-martin** [comment]
Just to put one, someone mentioned in the Slack this summer that they found
us from the Facebook page, but as mentioned we don't have the ability to
maintain it. We could create a Facebook account using the root Gmail and
set it to only IFTTT being able to post to it

--
Christian Martin

**Comment by Tjzabel** [comment]
@ct-martin That is why posting once more about everywhere else we can be found would be a good idea. It would give those who only follow us on facebook a chance to continue following us, whether that be through the mailing list or other means. 

That being said, I don't think it is overly necessary to create an IFTTT hook just to post on facebook. We haven't used the page in years.

**Comment by Tjzabel** [comment]
@jwflory alrighty, I will follow up with them :+1:

**Comment by thenaterhood** [comment]
I'm about 90% sure I'm an admin.

**Comment by Tjzabel** [comment]
@thenaterhood When you get the time, could you please confirm whether or not you're an admin on the page?

**Comment by Tjzabel** [comment]
So *apparently* I've had admin access on the RITlug Facebook page for a while. Let me know what you think of this message to write to the page:
```
Hey guys!

Due to a long time of inactivity on this Facebook page, the current RITlug eboard has decided to archive the page.
If you wish to keep up to date with the happenings of RITlug, here are all the current places we can be found:

* [RITlug Website](https://ritlug.com/)
* [RITlug Slack](https://rit-lug.slack.com/)
* [CampusGroups](https://campusgroups.rit.edu)
* [GitHub](https://github.com/RITlug)
* [Twitter](https://twitter.com/RITlug)

Thanks,
- Tim Zabel | RITlug President https://ritlug.com

**Comment by jwflory** [comment]
@Tjzabel +1 to post.

I might only post a link to the website's "[Get Involved](https://ritlug.com/get-involved/)" page since that has all of our important info there (too many links can discourage people from clicking any). But this is a nitpick and honestly the number of people in the group (who are not connected to us elsewhere) is so small, we don't have to get into the weeds on this.

![Just do it.](http://adnews.com.br/public/img/noticias/novas/just-do-it-6888.jpg "Just do it.")

**Comment by repkam09** [comment]
Huh looks like I am an admin as well! I agree, post about the more up to date locations, and archive the group.

**Comment by Tjzabel** [comment]
I should have time to do this tonight or tomorrow. Once I get through today I'll have a lot more time :+1:

**Comment by jwflory** [comment]
@Tjzabel Did you get a chance to do this one yet?

**Comment by Tjzabel** [comment]
## Update
A final announcement has been posted on the [RITlug Facebook Group](https://www.facebook.com/groups/RITLUG/), and has been archived. 

At this point, the page will stay visible to others who wish to view the page, but there will be no more postings, likes, or additional members allowed.

With this being said, this issue is now closed :+1:
