### ISSUE TITLE
Discuss budget allocation with Clubs

### ISSUE THREAD

**Issue by icflournoy** [RITlug/tasks#67]
### Problem Summary
The club was given a budget amount lower than what we anticipated, given the guidance from clubs at the end of last year. The information was that budget allocations were done based on brackets, with a minimum that a recognized club would receive.  RITlug received half of this minimum and we want to confirm why, and if its related to the late check from fundraising last year (https://github.com/RITlug/tasks/issues/10).

**Comment by icflournoy** [comment]
### 2018-09-24 Eboard Meeting

#### Discussion
*What would we spend more money on?* Showing that we would use the extra funds to grow the club.
Eg:
- table cloth
- stickers
- domain years namecheap

#### Action Items
- Determine what we would spend the extra budget allocation on?
- Schedule meeting with club office / Frank to discuss the exact reason the club was granted a lower amount than what we anticipated. This information will prepare us for fundraising this year and leading into next year, so we are not surprised by any short budget allocations.

**Comment by ct-martin** [comment]
Adding server backups to costs

Also, when we talk to Frank we need to get a clear answer on what might
affect us next year.

--
Christian Martin (Phone)

**Comment by jrtechs** [comment]
# Eboard Meeting 10-1-18

We want to figure out the rules which the club office follows for the budget since they seem to be changing. Does this block us from using the current budget?

## Action Items
@jibby0 Is working on getting a meeting with club office.

Make a plan of what we are going to do with money.
@jibby0 is going to make a list of what we want to buy and estimated cost. Also note what is happening yearly.
- table cloth - one from hub for cost estimation
- new banner
- stickers - double what we got last year
- switch for CBET
- backups

**Comment by icflournoy** [comment]
### 2018-10-10 Eboard Meeting

#### Discussion
- Cost of banner can be justified as we do off-campus events which show good publicity for RIT
- As a whole club we attend:
  - Maker Faire - Off campus, publicly visible
  - Imagine RIT
  - Club Gala

Other costs each year:
- Stickers ($250-$300) - handed out at events, meetups, conferences
  Flock (international), OSSN, Imagine, general meetings, Maker Faire, FOSSCON
- Domain renewal
- Server backups

Fundraising:
- Jackets
- Dinner
  We are considering doing a dinner once per semester (up from once per year)

#### Action Items
@jibby0 and @icflournoy are meeting with Clubs on 2018-10-11
- How did last year's fundraising affect this year's budget allocation?

**Comment by jibby0** [comment]
### 2018-10-11 Club Office Meeting

@jibby0 and @icflournoy met with Club Office. In short:

- More clubs asked for a budget this year than in years past. However, the pool of money for club budgets did not increase. 
  - Club office said there's no RIT policy on what to do when the requests are larger than what's available, since it changes depending on how large a difference there is. Some factors considered were:
    - History of club transactions
    - Number of recorded events the club participated in
    - Requested budget from years past
- Budgets are decided in the summer. So There's no way we could have our budget increased for this academic year.
- We were not denied the full amount because of the check for the last FOSS family dinner going missing.
- If we were looking for more money for a large, important budget item, a proposal to SG would be our best bet. 
  - We were thinking tablecloth and stickers would be good for this, as they would be big at all our events, and reflect how RIT looks.

**Comment by icflournoy** [comment]
### 2018-10-17 Eboard Meeting
- This issue has reached its conclusion. 
- Stickers purchase tracked in https://github.com/RITlug/tasks/issues/83
- Tablecloth work tracked in https://github.com/RITlug/tasks/issues/35 - the idea here is that we can request money from SG to cover a specific item for a specific event.
- **action** @ct-martin will look into making a short-term tablecloth for the Maker Faire.
