### ISSUE TITLE
Planning a premier event

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#7]
## Summary

All clubs are allowed one "premier" event a semester by the RIT Clubs Office, which carries extra priority for booking a venue / promotional advertising. We could plan a "premier" event to help grow the club or build community

## Explanation

Since this is a relatively new concept, I think it would be cool for us to try out a "premier" event. I don't think we really need to go crazy on this just yet – as a concept, it could be an installfest, a mini hackathon, or something RITlug-y sort of event, but I'd be happy if we had 10-20 people show up for the duration of the event. So, this ticket is not about building a crazy, huge, campus-wide event (unless we think we're ready to tackle that sort of thing).

I see this as a very, very backburner topic, possibly for spring semester. But it would be cool for us to utilize our quota of one per year by trying to create some sort of new tradition or event that people enjoy or think is fun.

## Notes from along the way

* **BarCamp idea**
    * Reaching out to other departments about open source topics, like film / music students in liberal arts college

**Comment by jflory7** [comment]
Had a short conversation with @schneidy today about the old [BarCamp Rochester](http://barcamproc.org/). Could be an interesting event to try doing. Maybe @Schneidy can expand a bit more on what the structure of the event looked like in the past when it was running.

**Comment by schneidy** [comment]
BarCamp is an unconference where anyone who attended could talk about any subject they wanted. The schedule was created the morning of the event after introductions on a big paper grid that was filled with blank sheets. Most of the talks lasted about 20 minutes with a few minutes for Q&A and time to switch rooms. We ran a lightning talk session right after lunch for an hour for those attendees who didn't want to speak more than 5 minutes.

The Rochester event was originally organized by CSHers but was open to the community. Every classroom on the first floor of Golisano was reserved by us, including the auditorium and atrium. For a while, we ended up running the event twice a year. On average we ended up with 150-175 attendees. It did require some sponsorship, but various colleges from around campus chipped in.

Most of the talks were tech focused but weren't limited to it. Other talks that stand out in my mind include a history of piracy of books due to the Gutenberg Press, how to make cotton candy, music theory, and an introduction to Minecraft (when it had recently come out).

I still personally run into tech folks from around the Rochester community who really miss the event. We normally had a 60/40 split between students and members of the greater Rochester community.

You can still find some of the videos from the event on [Vimeo](https://vimeo.com/barcamproc) along with photos on [Flickr](https://www.flickr.com/photos/37533664@N06/) and [Facebook](https://www.facebook.com/BarCampRoc/).

Let me know if you still have questions about the event. It was one of my favorites to organize.

**Comment by jwflory** [comment]
Given the context of what we are trying to organize and accomplish in this coming year, I think there are other needs for us to focus on and address for the coming year of RITlug. Once other ongoing work and tasks are resolved, this ticket can be reopened or considered in the future, beyond 2019.
