### ISSUE TITLE
TigerOS development update from project team to eboard

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#70]
TigerOS development is having a slow time picking back up this semester. This ticket is a chance for eboard to check in with TigerOS team members at our eboard meeting and see what we can do to help and get things back on track.

**Comment by ct-martin** [comment]
TigerOS has a meeting time now. The biggest issue is getting CI set up, which is a WIP but dealing with issues of limited GitLab CE features and trying to restrict root access to servers.

**Comment by jrtechs** [comment]
# Eboard Meeting 10-1-18

Work on sorting out CI. We can build manually, but, it slows things down.

Updating the website to be dynamic and host the docs.

Wait for Tiger-OS team to have regular meetings and then follow up.

# Action Items
In thee weeks have a Tiger-OS presentation meeting during the Eboard meeting (10-24-18).

**Comment by ct-martin** [comment]
@jwflory #77 will help us get CI going if you can find the time

From meeting today, we have split up the priorities for our next release (the beta release) and have a rough target of f29. More details to come in the next few weeks.

Notes here: https://github.com/RITlug/TigerOS/wiki/Next-Meeting-Agenda/795c660e845ffa04d4d673b6b5b7e59af7800e11#meeting-103---special-agenda-ignore-everything-from-announcement-on

**Comment by jwflory** [comment]
> @jwflory #77 will help us get CI going if you can find the time

Done. :+1:

**Comment by ct-martin** [comment]
We discussed this today at the TigerOS meeting and decided to respond early since this month is busy and we have the tasks outlined. TigerOS development is moving again and we are targeting a release of the end of October. As it stands right now we have the resources that eboard can give us to continue and the biggest issue is personal bandwidth due to classwork, working part- or full-time, and job applications for graduating members. We have cleaned up our issues and re-prioritized over the past couple weeks in order to best accommodate this. Additionally, we are discussing processes which can be implemented to reduce the human factor of project development to speed and things. While this will take some time, it will help the project immensely. We feel that this issue can be closed as it stands now.

**Comment by jwflory** [comment]
> We feel that this issue can be closed as it stands now.

I'd still like to do the eboard presentation. I haven't been involved for about a year so I am really curious to see where things are these days. :smile: Since I talk about TigerOS to a good number of folks outside of RIT, it would be helpful for me to also get my facts straight too.

**Comment by ct-martin** [comment]
In that case I would propose moving back the presentation until mid/late November to let us get this release finished and map out where we're going to focus for the rest of the semester. October is also a busy month for team members and we don't have bandwidth to make a presentation, much less a proper one, right now.

**Comment by icflournoy** [comment]
### 2018-10-10 Eboard Meeting

####  Discussion
Reviewed at meeting. We will tentatively anticipate a more formal TigerOS presentation in November eboard meeting, after the release at the end of October.

**Comment by jwflory** [comment]
I think we should keep this issue open until we have the presentation. I renamed the title of this issue and updated the metadata.
