### ISSUE TITLE
Schedule additional eboard meetings

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#79]
From discussions in eboard we have realized there are some big-item things that we don't have time to have a proper discussion on in a regular eboard meeting, and would thus require a dedicated meeting. The topics are as follows:

* Infra
  * Status update
    * Website (summer)
    * Email (CampusGroups, Google Groups, FOSSRIT)
    * CBET
    * Nextcloud
  * Current plan for infra (mainly CBET), including how it can benefit projects
* Projects
  * What can RITlug offer?
    * Infra? Knowledge base? Helping with setting up things like a website or docs?
  * What are the qualifications for a new project?
  * What is the on-boarding process for a new project?
* Long-term planning (a la #63)
* Review of processes to see what can be optimized (likely by automation) or what can be simplified (such as being friendlier to new contributors; see also: runbook)

**Comment by jwflory** [comment]
A special-topic meeting would be helpful for us to dedicate a set amount of time to work on something with all eboard members present. I suggest the next step to start with projects, since our projects inform all other topics (planning based on set of expectations from projects, leaves room for projects becoming more significant part of our general meetings in the future).

I'd prefer to do this on a weekend. We could meet somewhere like Fuego or on campus. I'm free most of this weekend if we wanted to do it on the 13th or 14th.

**Comment by Tjzabel** [comment]
I am free this weekend as well if we wanted to do a call.

**Comment by ct-martin** [comment]
I have enough space for the members here if we want to do at my place this
weekend.

--
Christian Martin (Phone)

**Comment by ct-martin** [comment]
Updating issue: we're meeting on-campus tomorrow for talking about infra & projects

**Comment by icflournoy** [comment]
# Notes from 2018-10-13 special meeting

## Infrastructure

**action**: @ct-martin will put together an Infrastructure roadmap.

### Website
Website was updated over the summer:
- Re-skinned, some small functional changes as well
- New projects section to showcase past and present RITlug projects
  **action**: @icflournoy to work on https://github.com/RITlug/ritlug.github.io/issues/153 to gather old projects from past members.
- Will be depreciating announcements page since we have moved to CampusGroups for mailings
- **action**: @jrtechs to work on https://github.com/RITlug/ritlug.github.io/issues/157 adding an Events page

### Email
- Issues last semester with RIT email filters blocking our emails
- We have moved to CampusGroups for mailings and the RIT email filter does not block these mails
- Still have public google groups to mail alumni/maintain public archive of mailings.
- @ct-martin will be keeping an eye on how CampusGroups functions with regards to
  - Does the mailing list get automatically updated based on membership status?
    ie. will new members get emails?
- Idea? forwarding to FOSSRIT mailing list
  - This list will be moving to discord in the near future
- We should send out a notification to the ritlug google groups list annoucing its closure

### CBET datacenter
RITlug is working towards operating its own hardware in the CBET datacenter.
The idea to to host services from this hardware for the club and its projects.
The CBET infrastructure is in addition to the Titan server where RITlug currently runs production services.

- It's a converted telephone closet in a basement.
- We have a few servers there. @ct-martin is working on getting functioning installs and network config
- UPS batteries need to be recycled
  This can be done at Batteries+, WasteManagement EcoPark, sometimes there are collections on campus
- **action**: @icflournoy will report to @ct-martin specs of gigabit switch he has to offer the club (https://github.com/RITlug/tasks/issues/72)
- **action**: @ct-martin schedules next trip to the datacenter (https://github.com/RITlug/tasks/issues/76)
- Dr. Skuse says to remove any hardware we are not using

#### Titan
- RITlug CLAWS account has reached the IP limit (all allocations go to Titan services)
- Solomon arranged for an IP address limit increase for RITlug during his time at ITS
- Will need additional IPs to get CBET online
- **action**: @jwflory has reached out to Solomon to start the process of getting additional IPs for the club CLAWS account
- **action**: As a short term workaround @ct-martin is going to try registering a device under his student CLAWS so that he can remotely access CBET servers

### NextCloud
RITlug currently uses Google Drive and it would be nice to move to an open source solution.
We are evaluating NextCloud as a replacement for Google Drive.

- **action**: @tzabel to reset @ct-martin's shell account on NextCloud instance
- **action**: @ct-martin to create eboard member's accounts on NextCloud so that they can mess with it
- **action**: @ct-martin will drop a link of officially supported NextCloud applications


## Projects

### What can RITlug offer?
- Infra: VMs (Titan, CBET build environment)
- Knowledge: Open source, development, design, etc
- Organization: Website template, documentation template, project management
- Project page on RITlug main site

### What are we willing to commit?
- Templating for website, docs
- **action**: @jwflory to create a single project quickstart repo under RITlug.
  Will review work at Nov 7th Eboard meeting

### Why would a project join RITlug?
@jwflory asked "Are we looking to start new projects, or take on existing ones?"
- A: take on existing ones. 

### What does RITlug get out of having projects under our umbrella?
- Community of students and projects
- Shows we do things
- Presentable (both for the project maintainer - "hey my project is an official RITlug project")
- Employers can see an affiliation

### What are qualifications for a new project?

### What is the onboarding process?
- Do we move source code under our org? Probably optional...

## Long term club planning (https://github.com/RITlug/tasks/issues/63)
The club should network with other groups on campus.
Co-hosting events would broaden reach and interests in open source and the club.
Coordinating events between other technical clubs.

**action**: Get involved in BrickHack in February. Can we be a resource at the event to help projects during that weekend?

**Comment by ct-martin** [comment]
@icflournoy: made some minor corrections (mostly spelling), thanks for posting

**Comment by ct-martin** [comment]
Updates:
* Email is working how it is supposed to and not how I was concerned it might
* Website has PRs for PDF embeds, an Events section, & deprecating announcements.

**Comment by jwflory** [comment]
> Email is working how it is supposed to and not how I was concerned it might

What do you mean? Is forwarding working for some lists?

> Website has PRs for PDF embeds, an Events section, & deprecating announcements.

:tada: :100: :tada:

**Comment by Tjzabel** [comment]
Do we still want to schedule additional eboard meetings?

**Comment by icflournoy** [comment]
### 2018-10-31 Eboard Meeting
- Will discuss when to hold next long-term planning meeting at the 11/7 eboard meeting

**Comment by jwflory** [comment]
As an update, we planned the #63 discussion for a two-hour special topic meeting on December 1st, 4pm-6pm. Notes specific to that meeting will go into #63.

**Comment by Tjzabel** [comment]
@RITlug/eboard-current Is there a possibility of moving this meeting to 3-5pm EST?

**Comment by jwflory** [comment]
@Tjzabel I can do that time.

**Comment by jwflory** [comment]
_Discussed in 2018-11-28 meeting._

We officially bumped the time back to 15:00-17:00 and we will meet in the MAGIC Suite of the new MAGIC building at RIT. Note you may need to use the Gannet entrance to get there since it's a Saturday and the building might be locked.

**Comment by Tjzabel** [comment]
@ct-martin Is this something you would still like to do? 

We are at the end of the semester, and I'm not sure what the status of this issue is. We can either  close out the issue, rename it to reflect a more specific purpose, or just remove the "review at meeting" label.

**Comment by Tjzabel** [comment]
Do we want to have an infrastructure meeting at some point to go over the current status of IPs and such?

**Comment by ct-martin** [comment]
@Tjzabel the last items for this issue was the meeting we had this weekend. We can talk in eboard about meeting ITS today. If we want to do anything else, that's beyond the scope of this issue and a new one should be filed.
